Repository raster-foundry/raster-foundry, pull requests merged in 2018-03, with the labels that each got.

#3046 Fix broken planet thumbnails.
  app-frontend/package.json
  app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
  app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
  app-frontend/src/app/pages/admin/platform/organizations/detail/detail.module.js
  app-frontend/src/app/services/scenes/planetRepository.service.js
  app-frontend/src/app/services/vendor/planetLabs.service.js
Labels: in review

#3050 Use BUILDCONFIG logo on share page
  app-frontend/src/app/pages/share/share.controller.js
Labels: in progress

#3057 Fix scene delete and scene display after being added issues
  app-frontend/src/app/pages/projects/edit/edit.module.js
Labels: in progress

#3060 Change acquisition date display to UTC
  app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
  app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
Labels: in progress

#3074 Fix broken logout button
  app-frontend/src/app/services/auth/auth.service.js
Labels: in progress

#3075 Fix colormodes
  app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
  app-frontend/src/app/pages/projects/edit/edit.module.js
Labels: in progress

#3078 Fix migration link location and migration content
  app-backend/migrations/src/main/scala/101.scala
  app-backend/migrations/src/main/scala/migrations/101.scala
  app-backend/migrations/src/main/scala/migrations/Summary.scala
  app-backend/migrations/src_migrations/main/scala/101.scala
Labels: in progress

#3082 Restore unintentionally removed migration config
  app-backend/migrations/src/main/resources/application.conf
Labels: in progress

#2998 Add frontend support for datasource licenses
  app-frontend/src/app/pages/imports/datasources/detail/detail.html
  app-frontend/src/app/pages/imports/datasources/detail/detail.module.js
  app-frontend/src/app/services/common/url.filter.js
  app-frontend/src/app/services/scenes/datasourceLicense.service.js
  app-frontend/src/app/services/services.module.js
  app-frontend/src/assets/styles/sass/_shame.scss
Labels: frontend, in progress

#3063 Enable copy confirmation on sharing buttons
  app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.html
  app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.module.js
  app-frontend/src/app/pages/projects/edit/sharing/sharing.html
  app-frontend/src/app/pages/projects/edit/sharing/sharing.module.js
  app-frontend/src/assets/styles/sass/_shame.scss
  app-frontend/src/assets/styles/sass/components/_button.scss
  app-frontend/src/assets/styles/sass/theme/high-contrast/components/_button.scss
Labels: in review

#3083 Add help center to show customer specific videos & docs
  app-frontend/config/webpack/helpDocs.json.template
  app-frontend/config/webpack/overrides.js.template
  app-frontend/package.json
  app-frontend/src/app/components/common/navBar/navBar.controller.js
  app-frontend/src/app/components/common/navBar/navBar.html
  app-frontend/src/app/components/common/navBar/navBar.module.js
  app-frontend/src/assets/styles/sass/components/_dropdown.scss
  app-frontend/src/assets/styles/sass/layout/_navbar.scss
  app-frontend/yarn.lock
Labels: in review

#3113 Treat Sentinel-2A/B as the same datasource in batch import and in DB
  app-backend/batch/src/main/resources/application.conf
  app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
  app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala
  app-backend/migrations/src/main/scala/migrations/102.scala
  app-backend/migrations/src/main/scala/migrations/Summary.scala
  app-backend/migrations/src_migrations/main/scala/102.scala
Labels: in progress

#3114 Get all paginated datasources upon scene browse
  app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js
Labels: in review
